GET http://127.0.0.1:3000/product-api/products

###
POST http://127.0.0.1:3000/user-api/users
Content-Type: application/json

{
    "id":200,
    "name":"ravi",
    "age":19
}


###
PUT http://127.0.0.1:3000/user-api/users/id
Content-Type: application/json

{
    "id":100,
    "name":"ravi",
    "age":20
}



### Read a user by id
GET http://localhost:3000/user-api/users/100



###
DELETE http://127.0.0.1:3000/user-api/users/id


###
DELETE http://127.0.0.1:3000/user-api/user/100



###
GET http://localhost:3000/product-api/products


###
POST http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":100,
    "name":"Laptop",
    "price":100000,
    "brand":"dell"
}


###
PUT http://localhost:3000/product-api/products
Content-Type: application/json

{
    "productId":100,
    "name":"Laptop",
    "price":200000,
    "brand":"dell"
}


### 
DELETE http://localhost:3000/product-api/products/100


